name: hellotori
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  animate_do: ^2.0.0
  cloud_firestore: ^1.0.1
  cupertino_icons: ^1.0.2
  firebase_auth: ^1.0.1
  firebase_core: ^1.0.1
  firebase_storage: ^8.0.0
  flutter_hex_color: ^2.0.0
  flutter_launcher_icons: ^0.9.0
  flutter_linkify: ^5.0.0
  flutter_local_notifications: ^5.0.0
  flutter_native_splash: ^1.1.7+1
  flutter_riverpod: ^0.13.1
  flutter_spinkit: ^5.0.0
  get: ^4.0.0-nullsafety.2
  google_sign_in: ^5.0.0
  gsheets: ^0.3.0-nullsafety.0
  http: ^0.13.1
  image_picker: ^0.7.3
  intl: ^0.17.0
  pinch_zoom: ^0.1.0-nullsafety.0
  share: ^2.0.1
  shared_preferences: ^2.0.3
  url_launcher: ^6.0.2
  webview_flutter: ^2.0.2
  youtube_plyr_iframe: ^2.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter_native_splash:
  color: "#fffffc"
  image: "assets/splash.png"
  android: true
  ios: true

flutter_icons:
  image_path: "assets/hellotori.png"
  android: true
  ios: true

flutter:
  uses-material-design: true

  assets:
    - assets/

  fonts:
    - family: EinaLight
      fonts:
        - asset: fonts/Eina01-Light.ttf
    - family: EinaRegular
      fonts:
        - asset: fonts/Eina01-Regular.ttf
    - family: EinaSemiBold
      fonts:
        - asset: fonts/Eina01-SemiBold.ttf
    - family: EinaBold
      fonts:
        - asset: fonts/Eina01-Bold.ttf
    - family: HelloTori
      fonts:
        - asset: fonts/HelloTori.ttf
