/// Flutter icons HelloTori
/// Copyright (C) 2021 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  HelloTori
///      fonts:
///       - asset: fonts/HelloTori.ttf
///
/// 
///
import 'package:flutter/widgets.dart';

class HelloTori {
  HelloTori._();

  static const _kFontFam = 'HelloTori';
  static const String? _kFontPkg = null;

  static const IconData chat = IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData back = IconData(0xe801, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData star = IconData(0xe802, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData check_false = IconData(0xe803, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData horn = IconData(0xe804, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData badge = IconData(0xe805, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData cross = IconData(0xe806, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData fullscreen = IconData(0xe807, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData heart_solid = IconData(0xe808, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
